### ISSUE TITLE
Issue exporting p12 file

### ISSUE THREAD

**Issue by lloydwatkin** [simpleweb/iOS-Development-For-Teams#3]
When exporting my p12 file I added a password for the certificate (very poor security from Apple here), then I entered my login keychain password to allow access. Upon clicking 'allow' ...**nothing**.

Turns out I needed to:
- Click on system keychain
- Go to 'certificates' in the left hand pane
- Find the `Apple Worldwide Developer Relations Certification Authority` cert
- Double click
- Expand the '**Trust**' section
- Set '**when using this certificate**' to '**Always Trust**'
- I could then export my p12 certificate

**Comment by dcorking** [comment]
Thank you Lloyd.

It looks like this only applies to App Distribution certificates. Developer and Push certificates seem to export in p12 format OK for me. Am I right?

Shall we add this to the main README.md ?

**Comment by lloydwatkin** [comment]
@dcorking its been quite a while so I really have no idea any more. Thankfully I haven't had to turn on the mac pretty much since then don't have a quick way to check.

@jacquesdev ?

**Comment by dcorking** [comment]
No problem Lloyd. And thanks again for the issue. I have pinged a couple of other committers to take a look.

**Comment by dcorking** [comment]
@daviddarnes ^ this suggestion looks right but I don't do iOS builds often enough to be sure. What do you think?

**Comment by daviddarnes** [comment]
@dcorking seems pretty reasonable to me, however it's best to check with the rest of the team. Since April 2016 it may have changed again 😶

**Comment by andoru** [comment]
@dcorking @daviddarnes This is oooooold, so I think it can die 🔪🎟

Adam updated the documentation just before he left and I am not aware of anyone in the team having issues like this since.
